# Generated by Django 3.1.7 on 2021-03-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210329_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.ManyToManyField(to='main.User'),
        ),
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='BoardUser',
        ),
    ]
