# Generated by Django 3.1.7 on 2021-03-29 16:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210329_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='invite_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
