# Generated by Django 3.1.7 on 2021-04-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210402_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
