# Generated by Django 3.1.7 on 2021-04-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_subtask_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_token',
            field=models.BinaryField(default=None),
            preserve_default=False,
        ),
    ]
