# Generated by Django 3.1.7 on 2021-04-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_user_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='name',
            field=models.CharField(default='Ponchique', max_length=35),
            preserve_default=False,
        ),
    ]
